language: python
python:
    - "3.5"
    - "3.6"
    - "3.7-dev"
install:
    - pip install --disable-pip-version-check --upgrade pip setuptools wheel
    - pip install -e .
script:
    - python setup.py test
